# Generated by Django 4.0.6 on 2022-08-08 04:54

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_list',
            field=models.CharField(default='1,2,3,4,5', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=10, null=True, unique=True, validators=[accounts.validators.validate_no_special_characters]),
        ),
    ]
