# Generated by Django 4.0.6 on 2022-08-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_picture_list_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_list',
            field=models.CharField(default='1 2 3 4 5', max_length=200),
        ),
    ]
