# Generated by Django 4.0.6 on 2022-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_picture_list_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_list',
            field=models.CharField(default='1 2 3 4', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
