# Generated by Django 4.1 on 2022-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_picture_list_alter_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture_list",
            field=models.CharField(default="6 7 8", max_length=200),
        ),
    ]
