# Generated by Django 4.0.6 on 2022-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_picture_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_list',
            field=models.CharField(default='1 2 3 4', max_length=200),
        ),
    ]
