# Generated by Django 4.0.6 on 2022-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0003_picture_picture_complete_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='tape',
            field=models.ImageField(null=True, upload_to='', verbose_name='테이프'),
        ),
    ]
