# Generated by Django 4.0.6 on 2022-08-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot', '0004_diary_tape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('tape_id', models.AutoField(primary_key=True, serialize=False)),
                ('tape_info', models.ImageField(upload_to='', verbose_name='tape')),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='tape',
        ),
        migrations.AddField(
            model_name='diary',
            name='foreign_key_tape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dot.tape'),
        ),
    ]
